# tasks file for deploy_tower
---
- name: Create install directory
  file:
    state: directory
    path: "{{ install_dir }}"

- name: Fetch installer
  get_url:
    url: "{{ download_url }}"
    dest: "{{ install_dir }}"

- name: Unarchive installer
  unarchive:
    remote_src: true
    src: "{{ install_dir }}/{{ installer_version }}.tar.gz"
    dest: "{{ install_dir }}"

- name: Deploy inventory file
  template:
    src: inventory.j2
    dest: "{{ install_dir }}/{{ installer_version }}/inventory"

- name: Check if Tower is runnning
  uri:
    url: "https://{{ ansible_facts['default_ipv4']['address'] }}/api/v2/ping/"
    method: GET
    validate_certs: false
  register: command_result
  ignore_errors: true

- name: Execute setup shell script
  command: "sh setup.sh"
  args:
    chdir: "{{ install_dir }}/{{ installer_version }}"
  ignore_errors: true
  when: command_result['status'] != 200

- name: Post Tower License
  uri:
    url: "https://{{ ansible_facts['default_ipv4']['address'] }}/api/v2/config/"
    method: POST
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
    user: "admin"
    password: "{{ admin_password }}"
    force_basic_auth: true
    body_format: json
    body: "{{ lookup('file', license_file) }}"
    validate_certs: false
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
